# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acesar-l <acesar-l@student.42sp.org.br>       +#+  +:+       +#+      #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/01 12:02:42 by acesar-l          #+#    #+#              #
#    Updated: 2022/02/01 12:17:31 by acesar-l         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

basics:
			chomd a+x *
			./install_packages.sh
			./set_passwdpolicy.sh
			./set_loginuser.sh
			
.PHONY:		basics
